kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: host.docker.internal
  share: /nfsshare
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
