apiVersion: v1
kind: Pod
metadata:
    name: nginx
    labels:
      app: kubia
spec:
    containers:
    - image: nginx:latest
      name: nginx
      ports: 
      - containerPort: 80
        hostPort: 80
        protocol: TCP